language: node_js

node_js:
  - v6

branches:
  only:
    - master

# cache:
#   bundler: true
#   directories:
#     - node_modules # NPM packages

notifications:
  email:
    on_failure: change
    on_success: change

script:
  - npm run test:cov

addons:
  code_climate:
    repo_token: $CODE_CLIMATE

after_success:
  - npm run codecov
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
