stages:
  - build
  - unit_tests
  - deploy_staging
  - ui_tests
  - build_production
  - deploy_production

# To cache both npm modules and Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  npm_config_cache: $CI_PROJECT_DIR/.npm
  CYPRESS_CACHE_FOLDER: $CI_PROJECT_DIR/cache/Cypress
  HUSKY_SKIP_INSTALL: 1

# Shared Settings
## Cache dependencies across jobs only pulling not uploading (upload to cache
## happens in build stage)
cache:
  key: $CI_COMMIT_REF_SLUG
  policy: pull # only pull cache, skip uploading
  paths:
    - .npm

## Install dependencies for React App and Cloud Functions. Installing of
## Cypress binary is skipped (done in E2E Testing Stage)
## Script run before all stages unless otherwise overriden
before_script:
  - CYPRESS_INSTALL_BINARY=0 npm ci
  - npm ci --prefix functions

# Build Stage
## Installs dependencies, builds app, and saves results for later (artifacts).
Build:
  stage: build
  image: node:10
  when: always
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-build/
  artifacts:
    name: $CI_JOB_STAGE-$CI_COMMIT_REF_SLUG
    expire_in: 2 weeks
    when: always
    paths:
      - build
  # Override cache behavior set above since we want to both pull and push to
  # the cache (no "policy" provided since pull-push is default)
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm
  script:
    - npm run build:config # create env specific src/config.js
    - npm run lint
    - npm run build

# Unit Testing Stage

## Cloud Functions Unit Tests (Mocha/Chai)
Function Tests:
  stage: unit_tests
  image: node:10
  when: on_success
  allow_failure: true
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-unit-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-functions-tests/
  artifacts:
    name: $CI_JOB_STAGE-$CI_COMMIT_REF_SLUG
    expire_in: 2 weeks
    when: always
    paths:
      - functions/dist
      - functions/coverage # Test coverage report
  dependencies:
    - Build
  before_script:
    - npm ci --prefix functions
  script:
    - npm run test:cov --prefix functions

## React Components Unit + Snapshot Tests (Jest)
Component Tests:
  stage: unit_tests
  image: node:10
  when: on_success
  allow_failure: true
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-unit-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-component-tests/
  artifacts:
    name: $CI_JOB_STAGE-$CI_COMMIT_REF_SLUG
    expire_in: 2 weeks
    when: always
    paths:
      - coverage
  dependencies:
    - Build
  script:
    - npm run test

# Deploy Staging Stage
## Deploy React App and Firebase Functions
Deploy Staging:
  stage: deploy_staging
  image: node:10
  environment:
    name: staging
    url: https://redux-firestore-stage.firebaseapp.com
  when: on_success
  only:
    - master
    - web
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-deploy/
      - $CI_COMMIT_MESSAGE =~ /skip-stage-deploy/
  artifacts:
    name: $CI_JOB_STAGE-$CI_COMMIT_REF_SLUG
    expire_in: 1 weeks
    when: on_failure
    paths:
      - firebase-debug.log
  dependencies:
    - Build
  script:
    - npm run deploy

# UI Tests Stage
## Install Cypress binary and run end to end tests using Cypress
UI Tests:
  stage: ui_tests
  image: cypress/base:10
  when: on_success
  allow_failure: true
  only:
    - master
    - web
    - schedules
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-tests/
      - $CI_COMMIT_MESSAGE =~ /skip-ui-tests/
  # Override cache behavior set above since we want to both pull and push to
  # the cache (no "policy" provided since pull-push is default)
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm
      - cache/Cypress
  artifacts:
    name: $CI_JOB_STAGE-$CI_COMMIT_REF_SLUG
    expire_in: 2 weeks
    when: always
    paths:
      - cypress/videos
      - cypress/screenshots
      - cypress.env.json
  dependencies:
    - Build
  # Override before_script behavior set above since we want to install the
  # Cypress Binary
  before_script:
     # Install deps including Cypress binary (skipped in default before_script)
    - npm ci
    - npm ci cypress
    # Confirm Cypress is ready to use
    - $(npm bin)/cypress verify
  script:
     # Create environment specific test config including auth token
     # (saved to cypress.env.json) then run E2E Tests through Cypress
    - npm run test:stage -- --record --key $CYPRESS_KEY

# Build Production Stage
## Build production version of bundle (has different config)
Build Production:
  stage: build_production
  image: node:10
  when: on_success
  only:
    - master
    - prod
    - web
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-deploy/
      - $CI_COMMIT_MESSAGE =~ /skip-prod-deploy/
  artifacts:
    name: $CI_JOB_STAGE-$CI_COMMIT_REF_SLUG
    expire_in: 1 week
    when: always
    paths:
      - build
  script:
    - npm run clean # remove existing dist folder
    - npm run build:config # create env specific src/config.js
    - npm run build # rebuild bundle with new config
    # Note: Functions are not rebuilt since a bundle with env specific config
    # is not created as with React App

# Deploy Production Stage
## Deploy React App and Cloud Functions to production environment
Deploy Production:
  stage: deploy_production
  image: node:10
  environment:
    name: production
    url: https://redux-firestore.firebaseapp.com
  when: manual # Only allow run through button on Gitlab site
  only:
    - master
    - prod
    - web
  variables:
    FIREBASE_CI_PROJECT: prod # deploy using prod project in .firebaserc
  artifacts:
    name: $CI_JOB_STAGE-$CI_COMMIT_REF_SLUG
    expire_in: 1 week
    when: on_failure
    paths:
      - firebase-debug.log
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-deploy/
      - $CI_COMMIT_MESSAGE =~ /skip-prod-deploy/
  script:
    - npm run deploy # Deploy Cloud Functions and React App (Firebase Hosting)
